### ISSUE TITLE
Choice <> Lions NFT Bash

### ISSUE THREAD

**Issue by ChoiceCoin** [ChoiceCoin/NFTs#33]
Choice Coin and Lion Coin are collaborating to provide rewards for an NFT Bash. The Bash will reward contributions to the Choice Coin GitHub in the NFT Repo, which will be forked by @LionsRoarRealLoud for future collaborations and developments. The contest will have two categories, the Bash which will focus on software development, and the NFTs contest will focus on aesthetics and art. Winners will be declared and rewarded on Discord within 24 hours of the Deadline. 

**Rewards**
First Prize: 444,000.00 Choice | 440.00 Lions | Gold Badge
Second Prize 250,000.00 Choice | 300.00 Lions | Silver Badge
Third Prize: 125,000.00 Choice | 250.00 Lions | Bronze Badge
Best Choice Coin NFT: 150,000.00 Choice
Best Lion Coin NFT: 350.00 Lions

**Bash Rules**

1. Make a PR with all files in one folder with the title,`[UserName_Bash]`. For example, `ChoiceCoin_Bash`.
2. The folder must be added to the `Choice_Lions_Bash` folder in the Choice Coin NFT repo.
3. You may use any programming language or blockchain.
4. Your contribution must include software files necessary for creating a Choice Coin or Lion Coin NFT.
5. Your contribution must include a Choice Coin or Lion Coin NFT.
6. Deadline January, 28, 11:00AM PT.
7. Winners will be judged on the simplicity of the code, utility, and design.
8. Contributions must include a `readme.md` file with run steps.
9. The goal for the bash is to produce an easy to use software where users can send Choice to generate an NFT.
10. The software should allow for users to upload files, allocate Choice, push a button, and generate an on chain NFT.

**NFT Rules**

1. Make a PR with all files in one folder with the title, `[UserName_NFT]`. For example, `ChoiceCoin_NFT`.
2. The folder must be added to the `Choice_Lions_Bash` folder in the Choice Coin NFT repo.
3. Your contribution must include a Choice Coin or Lion Coin NFT.
4. Deadline January, 28, 11:00AM PT
5. The goal for the NFT contest is to produce the best artistic NFT for Lion Coin and Choice Coin respectively.

**Comment by toycom** [comment]
Nice, which I had time today for it?

**Comment by MoonX-Hub** [comment]
This is an opportunity for me to give Choice Awards a try, I hope for good results 💯

**Comment by Ecool999** [comment]
Time for some creativity

**Comment by francischimes** [comment]
Nice one

**Comment by ChoiceCoin** [comment]
**Results**

First Prize: @farsh268 | Gold
Second Prize: @prince-hope1975 | Silver
Third Prize: @Samuellyworld | @Temitopeishola | Bronze
Fourth Prize: @ChukwuemekaKingsley | @eugenennamdi | Bronze

Best Choice NFT: @farsh268 
Best Lions NFT: @farsh268 

_Fourth prize was added and the reward will include 10,000.00 Choice, 100 Lions, and the Bronze Badge._
